using Orchard.ContentManagement;
using Orchard.Security;
using Orchard.UI.Admin;
using Orchard.DisplayManagement;
using Orchard.Localization;
using Orchard.Services;
using System.Web.Mvc;
using Orchard.Mvc.Filters;
﻿// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Orchard.Specs
{
    using TechTalk.SpecFlow;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Blog")]
    public partial class BlogFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
#line 1 "Blogs.feature"
#line hidden
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Blog", "  In order to add blogs to my site\r\n  As an author\r\n  I want to create blogs and " +
                    "create, publish and edit blog posts", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
            testRunner.OnFeatureEnd();
            testRunner = null;
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
            testRunner.OnScenarioEnd();
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo);
        public virtual void ScenarioCleanup()
            testRunner.CollectScenarioErrors();
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("In the admin (menu) there is a link to create a Blog")]
        public virtual void InTheAdminMenuThereIsALinkToCreateABlog()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("In the admin (menu) there is a link to create a Blog", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
    testRunner.Given("I have installed Orchard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
    testRunner.When("I go to \"admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
    testRunner.Then("I should see \"<a[^>]*href=\"/Admin/Blogs/Create\"[^>]*>Blog</a>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        [NUnit.Framework.DescriptionAttribute("I can create a new blog and blog post")]
        public virtual void ICanCreateANewBlogAndBlogPost()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can create a new blog and blog post", ((string[])(null)));
#line 11
#line 12
#line 13
    testRunner.When("I go to \"admin/blogs/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table1.AddRow(new string[] {
                        "Title.Title",
                        "My Blog"});
#line 14
        testRunner.And("I fill in", ((string)(null)), table1, "And ");
#line 17
        testRunner.And("I hit \"Publish\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
        testRunner.And("I go to \"admin/blogs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
        testRunner.And("I follow \"My Blog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
        testRunner.And("I follow \"New Post\" where class name has \"primaryAction\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
            table2.AddRow(new string[] {
                        "My Post"});
                        "Body.Text",
                        "Hi there."});
#line 21
        testRunner.And("I fill in", ((string)(null)), table2, "And ");
#line 25
#line 26
        testRunner.And("I am redirected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
    testRunner.Then("I should see \"Your Blog Post has been created.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
    testRunner.When("I go to \"my-blog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
    testRunner.Then("I should see \"<h1[^>]*>.*?My Blog.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
        testRunner.And("I should see \"<h1[^>]*>.*?My Post.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
    testRunner.When("I go to \"my-blog/my-post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
    testRunner.Then("I should see \"<h1[^>]*>.*?My Post.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
        testRunner.And("I should see \"Hi there.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
        [NUnit.Framework.DescriptionAttribute("I can create a new blog with multiple blog posts each with the same title and uni" +
            "que slugs are generated or given for said posts")]
        public virtual void ICanCreateANewBlogWithMultipleBlogPostsEachWithTheSameTitleAndUniqueSlugsAreGeneratedOrGivenForSaidPosts()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can create a new blog with multiple blog posts each with the same title and uni" +
                    "que slugs are generated or given for said posts", ((string[])(null)));
#line 35
#line 36
#line 37
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
            table3.AddRow(new string[] {
#line 38
        testRunner.And("I fill in", ((string)(null)), table3, "And ");
#line 41
#line 42
#line 43
#line 44
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
            table4.AddRow(new string[] {
#line 45
        testRunner.And("I fill in", ((string)(null)), table4, "And ");
#line 49
#line 50
        testRunner.And("I go to \"my-blog/my-post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
#line 52
#line 53
    testRunner.When("I go to \"admin/blogs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
#line 55
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
            table5.AddRow(new string[] {
                        "Hi there, again."});
#line 56
        testRunner.And("I fill in", ((string)(null)), table5, "And ");
#line 60
#line 61
        testRunner.And("I go to \"my-blog/my-post-2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
#line 63
        testRunner.And("I should see \"Hi there, again.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
#line 65
#line 66
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
            table6.AddRow(new string[] {
                        "AutoroutePart.CurrentUrl",
                        "my-blog/my-post"});
                        "Are you still there?"});
#line 67
        testRunner.And("I fill in", ((string)(null)), table6, "And ");
#line 72
#line 73
        testRunner.And("I go to \"my-blog/my-post-3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
#line 75
        testRunner.And("I should see \"Are you still there?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
        [NUnit.Framework.DescriptionAttribute("When viewing a blog the user agent is given an RSS feed of the blog\'s posts")]
        public virtual void WhenViewingABlogTheUserAgentIsGivenAnRSSFeedOfTheBlogSPosts()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When viewing a blog the user agent is given an RSS feed of the blog\'s posts", ((string[])(null)));
#line 77
#line 78
#line 79
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
            table7.AddRow(new string[] {
#line 80
        testRunner.And("I fill in", ((string)(null)), table7, "And ");
#line 83
#line 84
#line 85
#line 86
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
            table8.AddRow(new string[] {
#line 87
        testRunner.And("I fill in", ((string)(null)), table8, "And ");
#line 91
#line 92
#line 93
#line 94
    testRunner.Then("I should see \"<link rel=\"alternate\" type=\"application/rss\\+xml\" title=\"My Blog\" h" +
                    "ref=\"/rss\\?containerid=\\d+\" />\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
        [NUnit.Framework.DescriptionAttribute("Enabling remote blog publishing inserts the appropriate metaweblogapi markup into" +
            " the blog\'s page")]
        public virtual void EnablingRemoteBlogPublishingInsertsTheAppropriateMetaweblogapiMarkupIntoTheBlogSPage()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enabling remote blog publishing inserts the appropriate metaweblogapi markup into" +
                    " the blog\'s page", ((string[])(null)));
#line 96
#line 97
#line 98
        testRunner.And("I have enabled \"XmlRpc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
        testRunner.And("I have enabled \"Orchard.Blogs.RemotePublishing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
            table9.AddRow(new string[] {
#line 101
        testRunner.And("I fill in", ((string)(null)), table9, "And ");
#line 104
#line 105
        testRunner.And("I go to \"my-blog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
    testRunner.Then("I should see \"<link href=\"[^\"]*/XmlRpc/LiveWriter/Manifest\" rel=\"wlwmanifest\" typ" +
                    "e=\"application/wlwmanifest\\+xml\" />\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
    testRunner.When("I go to \"/XmlRpc/LiveWriter/Manifest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 108
    testRunner.Then("the content type should be \"\\btext/xml\\b\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
        testRunner.And("I should see \"<manifest xmlns=\"http\\://schemas\\.microsoft\\.com/wlw/manifest/weblo" +
                    "g\">\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
        testRunner.And("I should see \"<clientType>Metaweblog</clientType>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
        [NUnit.Framework.DescriptionAttribute("The virtual path of my installation when not at the root is reflected in the URL " +
            "example for the slug field when creating a blog or blog post")]
        public virtual void TheVirtualPathOfMyInstallationWhenNotAtTheRootIsReflectedInTheURLExampleForTheSlugFieldWhenCreatingABlogOrBlogPost()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The virtual path of my installation when not at the root is reflected in the URL " +
                    "example for the slug field when creating a blog or blog post", ((string[])(null)));
#line 112
#line 113
    testRunner.Given("I have installed Orchard at \"/OrchardLocal\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 114
#line 115
    testRunner.Then("I should see \"<span>http\\://localhost/OrchardLocal/</span>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
            table10.AddRow(new string[] {
#line 116
    testRunner.When("I fill in", ((string)(null)), table10, "When ");
#line 119
#line 120
#line 121
#line 122
#line 123
        [NUnit.Framework.DescriptionAttribute("The virtual path of my installation when at the root is reflected in the URL exam" +
            "ple for the slug field when creating a blog or blog post")]
        public virtual void TheVirtualPathOfMyInstallationWhenAtTheRootIsReflectedInTheURLExampleForTheSlugFieldWhenCreatingABlogOrBlogPost()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The virtual path of my installation when at the root is reflected in the URL exam" +
                    "ple for the slug field when creating a blog or blog post", ((string[])(null)));
#line 125
#line 126
    testRunner.Given("I have installed Orchard at \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 127
#line 128
    testRunner.Then("I should see \"<span>http\\://localhost/</span>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
            table11.AddRow(new string[] {
#line 129
    testRunner.When("I fill in", ((string)(null)), table11, "When ");
#line 132
#line 133
#line 134
#line 135
#line 136
        [NUnit.Framework.DescriptionAttribute("I set my blog to be the content for the home page and the posts for the blog be r" +
            "ooted to the app")]
        public virtual void ISetMyBlogToBeTheContentForTheHomePageAndThePostsForTheBlogBeRootedToTheApp()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I set my blog to be the content for the home page and the posts for the blog be r" +
                    "ooted to the app", ((string[])(null)));
#line 138
#line 139
#line 140
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
            table12.AddRow(new string[] {
                        "AutoroutePart.PromoteToHomePage",
                        "true"});
#line 141
        testRunner.And("I fill in", ((string)(null)), table12, "And ");
#line 145
#line 146
#line 147
#line 148
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
            table13.AddRow(new string[] {
#line 149
        testRunner.And("I fill in", ((string)(null)), table13, "And ");
#line 153
#line 154
#line 155
        testRunner.And("I go to \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
    testRunner.Then("I should see \"<h1>My Blog</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 157
    testRunner.When("I go to \"/my-blog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
    testRunner.Then("the status should be 200 \"OK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 159
    testRunner.When("I go to \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 160
#line 161
    testRunner.When("I go to \"/my-post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 162
    testRunner.Then("I should see \"<h1>My Post</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
        [NUnit.Framework.DescriptionAttribute("I can create browse blog posts on several pages")]
        public virtual void ICanCreateBrowseBlogPostsOnSeveralPages()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can create browse blog posts on several pages", ((string[])(null)));
#line 164
#line 165
#line 166
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
            table14.AddRow(new string[] {
#line 167
        testRunner.And("I fill in", ((string)(null)), table14, "And ");
#line 170
#line 171
#line 172
#line 173
#line 174
        testRunner.And("I wait \"1000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
            table15.AddRow(new string[] {
                        "My Post 1"});
#line 175
        testRunner.And("I fill in", ((string)(null)), table15, "And ");
#line 178
#line 179
#line 180
#line 181
#line 182
#line 183
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
            table16.AddRow(new string[] {
                        "My Post 2"});
#line 184
        testRunner.And("I fill in", ((string)(null)), table16, "And ");
#line 187
#line 188
#line 189
#line 190
#line 191
#line 192
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
            table17.AddRow(new string[] {
                        "My Post 3"});
#line 193
        testRunner.And("I fill in", ((string)(null)), table17, "And ");
#line 196
#line 197
#line 198
#line 199
#line 200
#line 201
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
            table18.AddRow(new string[] {
                        "My Post 4"});
#line 202
        testRunner.And("I fill in", ((string)(null)), table18, "And ");
#line 205
#line 206
#line 207
#line 208
#line 209
#line 210
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
            table19.AddRow(new string[] {
                        "My Post 5"});
#line 211
        testRunner.And("I fill in", ((string)(null)), table19, "And ");
#line 214
#line 215
#line 216
#line 217
#line 218
#line 219
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
            table20.AddRow(new string[] {
                        "My Post 6"});
#line 220
        testRunner.And("I fill in", ((string)(null)), table20, "And ");
#line 223
#line 224
#line 225
#line 226
#line 227
#line 228
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
            table21.AddRow(new string[] {
                        "My Post 7"});
#line 229
        testRunner.And("I fill in", ((string)(null)), table21, "And ");
#line 232
#line 233
#line 234
#line 235
#line 236
#line 237
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
            table22.AddRow(new string[] {
                        "My Post 8"});
#line 238
        testRunner.And("I fill in", ((string)(null)), table22, "And ");
#line 241
#line 242
#line 243
#line 244
#line 245
#line 246
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
            table23.AddRow(new string[] {
                        "My Post 9"});
#line 247
        testRunner.And("I fill in", ((string)(null)), table23, "And ");
#line 250
#line 251
#line 252
#line 253
#line 254
#line 255
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
            table24.AddRow(new string[] {
                        "My Post 10"});
#line 256
        testRunner.And("I fill in", ((string)(null)), table24, "And ");
#line 259
#line 260
#line 261
#line 262
#line 263
#line 264
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
            table25.AddRow(new string[] {
                        "My Post 11"});
#line 265
        testRunner.And("I fill in", ((string)(null)), table25, "And ");
#line 268
#line 269
#line 270
#line 271
#line 272
#line 273
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
            table26.AddRow(new string[] {
                        "My Post 12"});
#line 274
        testRunner.And("I fill in", ((string)(null)), table26, "And ");
#line 277
#line 278
#line 279
#line 280
#line 281
#line 282
        testRunner.And("I should see \"<h1[^>]*>.*?My Post 12.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 283
        testRunner.And("I should see \"<h1[^>]*>.*?My Post 11.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 284
        testRunner.And("I should not see \"My Post 2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 285
    testRunner.When("I go to \"my-blog?page=2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 286
#line 287
        testRunner.And("I should see \"<h1[^>]*>.*?My Post 1.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 288
        testRunner.And("I should see \"<h1[^>]*>.*?My Post 2.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 289
        testRunner.And("I should not see \"My Post 3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
        [NUnit.Framework.DescriptionAttribute("I can create a new blog with a percent sign in the title and it gets stripped out" +
            " of the slug")]
        public virtual void ICanCreateANewBlogWithAPercentSignInTheTitleAndItGetsStrippedOutOfTheSlug()
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can create a new blog with a percent sign in the title and it gets stripped out" +
                    " of the slug", ((string[])(null)));
#line 291
#line 292
       testRunner.Given("I have installed Orchard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 293
       testRunner.When("I go to \"admin/blogs/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
            table27.AddRow(new string[] {
#line 294
       testRunner.And("I fill in", ((string)(null)), table27, "And ");
#line 297
       testRunner.And("I hit \"Publish\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
       testRunner.And("I go to \"admin/blogs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 299
       testRunner.And("I follow \"My Blog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
       testRunner.And("I follow \"New Post\" where class name has \"primaryAction\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
            table28.AddRow(new string[] {
                        "My Post with a % Sign"});
#line 301
       testRunner.And("I fill in", ((string)(null)), table28, "And ");
#line 305
#line 306
       testRunner.And("I go to \"my-blog/my-post-with-a-sign\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 307
       testRunner.Then("I should see \"<h1[^>]*>.*?My Post with a % Sign.*?</h1>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 308
       testRunner.And("I should see \"Hi there.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
    }
}
#pragma warning restore
#endregion
