using Orchard.ContentManagement;
using Orchard.Security;
using Orchard.UI.Admin;
using Orchard.DisplayManagement;
using Orchard.Localization;
using Orchard.Services;
using System.Web.Mvc;
using Orchard.Mvc.Filters;
using System;
using System.Collections.Generic;
using Orchard.ContentManagement.Records;

namespace Orchard.ContentManagement {
    /// <summary>
    /// Reprensents dynamically created query on Content Items.
    /// </summary>
    public interface IHqlQuery {
        /// <summary>
        /// The underlying <see cref="ContentManager"/> instance used to execute the query.
        /// </summary>
        IContentManager ContentManager { get; }
        /// Add content type constraints to the query.
        IHqlQuery ForType(params string[] contentTypes);
        /// Eagerly fetches specific content parts.
        IHqlQuery Include(params string[] contentPartRecords);
        
        /// Adds versioning options to the query.
        IHqlQuery ForVersion(VersionOptions options);
        /// Defines the resulting type.
        /// <returns>An <see cref="IHqlQuery&lt;T&gt;"/></returns>
        IHqlQuery<T> ForPart<T>() where T : IContent;
        /// Executes the query and returns all results.
        IEnumerable<ContentItem> List();
        /// Executes the query and returns all ids for matching content items.
        IEnumerable<int> ListIds();
        /// Returns a subset of the matching content items.
        IEnumerable<ContentItem> Slice(int skip, int count);
        /// Returns the number of matching content items.
        int Count();
        /// Adds a join to a the query.
        /// <param name="alias">An expression pointing to the joined relationship.</param>
        IHqlQuery Join(Action<IAliasFactory> alias);
        /// Adds a where constraint to the query.
        /// <param name="predicate">A predicate expression.</param>
        IHqlQuery Where(Action<IAliasFactory> alias, Action<IHqlExpressionFactory> predicate);
        /// Adds a join to a specific relationship.
        /// <param name="order">An order expression.</param>
        IHqlQuery OrderBy(Action<IAliasFactory> alias, Action<IHqlSortFactory> order);
    }
    /// Reprensents dynamically created query on Content Items, having a specific Content Part.
    public interface IHqlQuery<TPart> where TPart : IContent {
        IHqlQuery<TPart> ForType(params string[] contentTypes);
        IHqlQuery<TPart> ForVersion(VersionOptions options);
        IEnumerable<TPart> List();
        IEnumerable<TPart> Slice(int skip, int count);
        IHqlQuery<TPart> Join(Action<IAliasFactory> alias);
        IHqlQuery<TPart> Where(Action<IAliasFactory> alias, Action<IHqlExpressionFactory> predicate);
        IHqlQuery<TPart> OrderBy(Action<IAliasFactory> alias, Action<IHqlSortFactory> order);
    public interface IAlias {
        /// The name of the alias.
        string Name { get; }
    public interface IAliasFactory {
        /// Creates a join on a content part record or returns it if it already exists.
        /// <param name="type">The type of join, e.g. "left outer join"</param>
        /// <param name="withPredicate">An expression for an additional constraint on the join</param>
        IAliasFactory ContentPartRecord<TRecord>(string type = null, Action<IHqlExpressionFactory> withPredicate = null) where TRecord : ContentPartRecord;
        /// <param name="contentPartRecord">The type of the part to join</param>
        IAliasFactory ContentPartRecord(Type contentPartRecord, string type = null, Action<IHqlExpressionFactory> withPredicate = null);
        /// Creates a join based on a property, or returns it if it already exists.
        IAliasFactory Property(string propertyName, string alias);
        /// Returns an existing alias by its name.
        IAliasFactory Named(string alias);
        /// Returns an the <see cref="ContentItemRecord"/> alias.
        IAliasFactory ContentItem();
        /// Returns an the <see cref="ContentItemVersionRecord"/> alias.
        IAliasFactory ContentItemVersion();
        /// Returns an the <see cref="ContentTypeRecord"/> alias.
        IAliasFactory ContentType();
    public interface IHqlSortFactory {
        /// Sorts by ascending order
        void Asc(string propertyName);
        /// Sorts by descending order
        void Desc(string propertyName);
        /// Sorts randomly
        void Random();
        /// Sort in ascending order, adding custom HQL strings
        /// to the SELECT and ORDER BY statements
        /// <param name="propertyName">Name of the property</param>
        /// <param name="additionalSelectOps">Additional HQL for the SELECT statement</param>
        /// <param name="additionalOrderOps">Additional HQL for the ORDER BY statement</param>
        /// <remarks>ORDER BY items must appear in the select list if SELECT DISTINCT is specified.
        /// If such query is being generated by the implementation (as is the case for DefaultHqlQuery),
        /// make sure to respect that constraint when generating the addtionalOrderOps and
        /// additionalSelectOps parameters.</remarks>
        void Asc(string propertyName, string additionalSelectOps, string additionalOrderOps);
        /// Sort in descending order, adding custom HQL strings
        void Desc(string propertyName, string additionalSelectOps, string additionalOrderOps);
}
